Add redirect when creating a post
Pterodactyls/Pterodactyls pull request #25
Opened 2017-11-25 23:01 UTC by rithnarin

nice little change

2017-11-25 23:04 UTC, vinojg approved these changes
Looks good to go

2017-11-26 01:04 UTC, vinojg approved these changes

2017-11-26 01:58 UTC, ephraimg requested changes
Looks good! Just a couple of typos in db/orm.js at line 66. Should be no comma at the end, and a stray ß appeared somehow at the end of the eslint comment.

2017-11-26 02:09 UTC, ephraimg approved these changes

2017-11-26 02:09 UTC, merged